[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Simon Sawert <simon@sawert.se>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.0.0"
