#!/bin/sh

set -eu

script_dir=$(dirname "$0")

day_no=$(( $(grep -n pub src/solutions/mod.rs | awk -F':' '{print $1}') - 1 ))
day=$(printf "day%02d" "$day_no")


[ -e "$script_dir/src/solutions/${day}.rs" ] && exit 1

echo "Remove this line and enter input for day $day_no" > "$script_dir/input/$day"
nvim "$script_dir/input/$day"

cp \
    "$script_dir/src/solutions/template.ignore" \
    "$script_dir/src/solutions/${day}.rs"

gsed -i "${day_no}i mod $day;" "$script_dir/src/solutions/mod.rs"
gsed -i "s/ $day_no => todo!()/ $day_no => $day::solve()/" "$script_dir/src/solutions/mod.rs"
gsed -i "s/__DAY__/$day_no/" "$script_dir/src/solutions/${day}.rs"
